# Generated by Django 5.2.10 on 2026-01-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
