# Generated by Django 5.2.10 on 2026-01-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
